### PR TITLE
Pushed All project files in development branch

### PR DESCRIPTION
**Pull request by akshay-rajput**
I would like my App.js file to be reviewed.

### CODE REVIEW

**Comment by knackofabhinav** [comment]
Looks great to me! You should work on making it more responsive.

**Comment by akshay-rajput** [comment]
> Looks great to me! You should work on making it more responsive.

I've updated the pull request where I've made it responsive.

**Comment by akshay-rajput** [comment]
Closing this pr as it has build related changes as well

**Comment by Akhil-Movva** [comment]
Great job! Too good and professionally done. 
Just a small suggestion:
In the navbar section, all navbars are not entirely visible in the mobile viewport-I am having to slide them to see the signup buttons. I feel it would be more good if you can make all the navbars to be completly visible in the mobile viewport.

**Comment by akshay-rajput** [comment]
> Great job! Too good and professionally done.
> Just a small suggestion:
> In the navbar section, all navbars are not entirely visible in the mobile viewport-I am having to slide them to see the signup buttons. I feel it would be more good if you can make all the navbars to be completly visible in the mobile viewport.

Thanks for reviewing, appreciate it. I'll work on it.

**Comment by akshay-rajput** [comment]
This is the final version of my documentation site. Fixed all UI related bugs, made it responsive, and added documentation for all classes as well.

**Pull request merged**
